@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}
@contentType = application/json

GET http://{{host}}/api/info

###

GET  http://{{host}}/api/persons

###

GET http://{{host}}/api/persons/63106983a5c9196698b7b68f

###

DELETE http://{{host}}/api/persons/63106983a5c9196698b7b68f

###

POST http://{{host}}/api/persons
Content-Type: {{contentType}}

{
  "name": "Arto Hellas",
  "number": "040-123456"
}

###

PUT http://{{host}}/api/persons/63105af736be451a80bd2d0d
Content-Type: {{contentType}}

{
  "name": "Ada Lovelace",
  "number": "12345678901"
}
